### ISSUE TITLE
Easier way to set the view height

### ISSUE THREAD

**Issue by brrd** [brrd/electron-tabs#175]
**Is your feature request related to a problem? Please describe.**
See #173

**Describe the solution you'd like**
```css
.etabs {
  height: 100%;
}

.views {
  height: calc(100% - 33px);
}
```

Then we would be able to do : 

```html
<div style="position: relative; height: 300px;">
  <tab-group new-tab-button="true" sortable="true">
  </tab-group>
</div>
<div class="footer">Footer</div>
```
